version: '3.7'

services:
  simple-retail-api:
    image: simple-retail-api
    build:
      context: .
      dockerfile: SimpleRetail.API/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - simple-retail-db

  simple-retail-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "S1mpleRetai!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"